# Generated by Django 6.0.4 on 2026-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("driver", "Driver"),
                    ("cook", "Cook"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
