# Generated by Django 6.0.4 on 2026-05-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_menuitems_menuitem_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
