# Generated by Django 6.0.4 on 2026-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("DELIVERY", "Delivery"), ("PICKUP", "Pickup")],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("CASH", "cash")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("COOKING", "Cooking"),
                            ("READY", "Ready"),
                            ("ON_THE_WAY", "On the way"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
