# Generated by Django 6.0.4 on 2026-05-21 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_tracking_token_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="driver",
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("DELIVERY", "Доставка"), ("PICKUP", "Самовивіз")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("ONLINE", "Онлайн"), ("CASH", "При отриманні")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Нове"),
                    ("CONFIRMED", "Підтверджено"),
                    ("COOKING", "Готується"),
                    ("READY", "Готово"),
                    ("ON_THE_WAY", "В дорозі"),
                    ("DELIVERED", "Доставлено"),
                    ("CANCELLED", "Скасовано"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
