# Generated by Django 6.0.4 on 2026-05-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0004_remove_order_driver_order_email_alter_order_customer_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tracking_token",
        ),
    ]
